// static mappings for the mega-menus
export const sportsData: Record<string,string[]> = {
  NHL: ['Lakers','Celtics','Rangers','Maple Leafs','Blackhawks','Flyers'],
  NBA: ['Warriors','Lakers','Celtics','Bulls','Heat','Heat'],
  NFL: ['Cowboys','Patriots','Packers','Chiefs','Giants','Bears'],
  MLB: ['Yankees','Dodgers','Red Sox','Cubs','Giants','Cardinals'],
  MLS: ['LA Galaxy','NYCFC','Seattle Sounders','Atlanta United','Portland Timbers'],
  NCAAFB: ['Ohio State','Alabama','Clemson','Notre Dame','Oklahoma','Texas'],
  NCAABB: ['Duke','Kentucky','UCLA','Kansas','Gonzaga','Michigan'],
};

export const concertData: Record<string,string[]> = {
  'Top Concerts': [
    'Taylor Swift',
    'Bad Bunny',
    'Beyoncé',
    'Drake',
    'Ed Sheeran',
    'The Weeknd',
    'Harry Styles',
    'Billie Eilish',
    'Coldplay',
    'Post Malone',
    'Adele',
    'Bruno Mars',
    'Kendrick Lamar',
    'Eminem',
    'Foo Fighters',
    'Red Hot Chili Peppers',
    'Dua Lipa',
    'Lady Gaga',
    'Justin Bieber',
    'Shawn Mendes',
    'Lorde',
    'Imagine Dragons',
    'Maroon 5',
    'Ariana Grande',
    'SZA',
    'BTS',
    'Blackpink',
  ],
};

export const theaterData: Record<string,string[]> = {
  'Top Theater': [
    'Hamilton',
    'Wicked',
    'The Lion King',
    'Aladdin',
    'Chicago',
    'Phantom of the Opera',
    'Mrs. Doubtfire',
    'Moulin Rouge',
    'MJ the Musical',
    'Dear Evan Hansen',
    'Hadestown',
    'The Book of Mormon',
    'Six',
    'Come From Away',
    'Kinky Boots',
    'The Curious Incident',
    'Mean Girls',
    'Beetlejuice',
    'Tina – The Tina Turner Musical',
    'Funny Girl',
    '& Juliet',
    'Diana the Musical',
    'Jagged Little Pill',
    'Frozen – The Broadway Musical',
    'Back to the Future',
  ],
};
