// src/app/components/_megaData.ts
export const sportsData = {
    NBA: [
      'Atlanta Hawks',
      'Boston Celtics',
      'Brooklyn Nets',
      'Charlotte Hornets',
      'Chicago Bulls',
      'Cleveland Cavaliers',
      'Dallas Mavericks',
      'Denver Nuggets',
      'Detroit Pistons',
      'Golden State Warriors',
      'Houston Rockets',
      'Indiana Pacers',
      'Los Angeles Clippers',
      'Los Angeles Lakers',
      'Memphis Grizzlies',
      'Miami Heat',
      'Milwaukee Bucks',
      'Minnesota Timberwolves',
      'New Orleans Pelicans',
      'New York Knicks',
      'Oklahoma City Thunder',
      'Orlando Magic',
      'Philadelphia 76ers',
      'Phoenix Suns',
      'Portland Trail Blazers',
      'Sacramento Kings',
      'San Antonio Spurs',
      'Toronto Raptors',
      'Utah Jazz',
      'Washington Wizards',
    ],
    MLB: [
      'Arizona Diamondbacks',
      'Atlanta Braves',
      'Baltimore Orioles',
      'Boston Red Sox',
      'Chicago Cubs',
      'Chicago White Sox',
      'Cincinnati Reds',
      'Cleveland Guardians',
      'Colorado Rockies',
      'Detroit Tigers',
      'Houston Astros',
      'Kansas City Royals',
      'Los Angeles Angels',
      'Los Angeles Dodgers',
      'Miami Marlins',
      'Milwaukee Brewers',
      'Minnesota Twins',
      'New York Mets',
      'New York Yankees',
      'Oakland Athletics',
      'Philadelphia Phillies',
      'Pittsburgh Pirates',
      'San Diego Padres',
      'San Francisco Giants',
      'Seattle Mariners',
      'St. Louis Cardinals',
      'Tampa Bay Rays',
      'Texas Rangers',
      'Toronto Blue Jays',
      'Washington Nationals',
    ],
    NFL: [
      'Arizona Cardinals',
      'Atlanta Falcons',
      'Baltimore Ravens',
      'Buffalo Bills',
      'Carolina Panthers',
      'Chicago Bears',
      'Cincinnati Bengals',
      'Cleveland Browns',
      'Dallas Cowboys',
      'Denver Broncos',
      'Detroit Lions',
      'Green Bay Packers',
      'Houston Texans',
      'Indianapolis Colts',
      'Jacksonville Jaguars',
      'Kansas City Chiefs',
      'Las Vegas Raiders',
      'Los Angeles Chargers',
      'Los Angeles Rams',
      'Miami Dolphins',
      'Minnesota Vikings',
      'New England Patriots',
      'New Orleans Saints',
      'New York Giants',
      'New York Jets',
      'Philadelphia Eagles',
      'Pittsburgh Steelers',
      'San Francisco 49ers',
      'Seattle Seahawks',
      'Tampa Bay Buccaneers',
      'Tennessee Titans',
      'Washington Commanders',
    ],
    CFB: [
      'Alabama Crimson Tide',
      'Clemson Tigers',
      'Ohio State Buckeyes',
      'Georgia Bulldogs',
      'Oklahoma Sooners',
      'LSU Tigers',
      'Notre Dame Fighting Irish',
      'Texas Longhorns',
      'Florida Gators',
      'USC Trojans',
      'Michigan Wolverines',
      'Penn State Nittany Lions',
      'Oregon Ducks',
      'Miami Hurricanes',
      'Wisconsin Badgers',
      'UCLA Bruins',
      'Auburn Tigers',
      'Texas A&M Aggies',
      'Washington Huskies',
      'Iowa Hawkeyes',
    ],
    MLS: [
      'Atlanta United FC',
      'Austin FC',
      'CF Montréal',
      'Charlotte FC',
      'Chicago Fire FC',
      'FC Cincinnati',
      'Colorado Rapids',
      'Columbus Crew',
      'D.C. United',
      'FC Dallas',
      'Houston Dynamo FC',
      'Inter Miami CF',
      'LA Galaxy',
      'Los Angeles FC',
      'Minnesota United FC',
      'Nashville SC',
      'New England Revolution',
      'New York City FC',
      'New York Red Bulls',
      'Orlando City SC',
      'Philadelphia Union',
      'Portland Timbers',
      'Real Salt Lake',
      'San Jose Earthquakes',
      'Seattle Sounders FC',
      'Sporting Kansas City',
      'St. Louis City SC',
      'Toronto FC',
      'Vancouver Whitecaps FC',
    ],
    NHL: [
      'Anaheim Ducks',
      'Arizona Coyotes',
      'Boston Bruins',
      'Buffalo Sabres',
      'Calgary Flames',
      'Carolina Hurricanes',
      'Chicago Blackhawks',
      'Colorado Avalanche',
      'Columbus Blue Jackets',
      'Dallas Stars',
      'Detroit Red Wings',
      'Edmonton Oilers',
      'Florida Panthers',
      'Los Angeles Kings',
      'Minnesota Wild',
      'Montreal Canadiens',
      'Nashville Predators',
      'New Jersey Devils',
      'New York Islanders',
      'New York Rangers',
      'Ottawa Senators',
      'Philadelphia Flyers',
      'Pittsburgh Penguins',
      'San Jose Sharks',
      'St. Louis Blues',
      'Tampa Bay Lightning',
      'Toronto Maple Leafs',
      'Vancouver Canucks',
      'Vegas Golden Knights',
      'Washington Capitals',
      'Winnipeg Jets',
    ],
    OTHER: [
      'UFC',
      'Bellator MMA',
      'WWE',
      'Premier League Soccer',
      'Formula 1',
      'NASCAR',
    ],
  };
  